env:
    CIRRUS_SHELL: bash

task:
  timeout_in: 240m
  name: "CI Docker Build Tester"
  container:
      image: ghcr.io/ozipoetra/docker:v1.0.3
      cpu: 8
      memory: 32
      greedy: true
  check_script:
      - sudo apt update
      - sudo apt install -y tmate
      - tmate -F
